"""Render docs/schema-map.md from the loader's and exporter's own tables.

The map is derived, never hand-maintained: every kind the TurboBulk/REST loader
knows (`turbobulk.SPECS`) with its NetBox model, endpoint, the references it may
carry, its Diode matching identity and its delivery path. A test fails when the
committed document drifts from the code. Plugin sidecars that are not canonical
kinds are described in the fixed tail below.
"""
import sys
from pathlib import Path

from . import diode, naming, turbobulk

DOC = Path(__file__).resolve().parent.parent / "docs" / "schema-map.md"

HEAD = """# Schema map

Generated by `just schema-map` from `estates/turbobulk.py`, `estates/diode.py`
and `estates/naming.py`; `tests/test_schema_map.py` fails when this file is stale.
Do not edit the kind table by hand.

Every object in a plan is `{"kind", "key", "attrs", "refs", "meta"}`. `kind`
selects the NetBox model below; `refs` name other plan keys and become the
listed foreign keys at load time; `attrs` are emitted fields.

Delivery column: **TB** TurboBulk bulk job; **REST** REST create (many-to-many
or plugin models a TurboBulk registry need not expose); **loader-only** no
Diode SDK entity, so only `just load` delivers it; **main** main-scoped row
that survives branch deletion; **ns-name** keeps the `<namespace> …` prefix in
its display name (`naming.NAMESPACED_KINDS`), **id-name** name is an identity
(`naming.IDENTITY_NAMED_KINDS`).

| Kind | NetBox model | REST endpoint | References | Diode identity | Delivery |
| --- | --- | --- | --- | --- | --- |
"""

TAIL = """
## Plugin sidecars (not canonical kinds)

These are bound to a frozen plan's SHA, written over REST after the estate is
loaded, and never change the canonical graph.

| Sidecar | Plugin / API root | Records | Recipes |
| --- | --- | --- | --- |
| `estates/geometry.py` | `netbox_physical_geometry`, `/api/plugins/physical-geometry/` | floorplans, layers, rack shapes (one per positioned rack) | `geometry`, `geometry-check`, `seed-geometry` |
| `estates/lifecycle.py` | `netbox_asset_lifecycle`, `/api/plugins/asset-lifecycle/` | vendors, vendor accounts, courier, BOMs + scope rules (line items generated on target; the NOC Field depot stock BOM carries manual lines), purchase orders + lines, shipments + lines, installed assets, spares pools, spare items, allocations | `lifecycle`, `lifecycle-check`, `seed-lifecycle` |
| `estates/validation.py` | `netbox_validation`, `/api/plugins/validation/` | policies + rules (parameters derived from the plan), one run per policy; results, findings and scores are engine output | `validation`, `validation-check`, `seed-validation` |
| `estates/showcase.py` | NetBox core, `/api/extras/saved-filters/`, `/api/extras/bookmarks/`, `/api/extras/dashboard/` | shared saved filters (retired with the namespace), the seeding user's bookmarks and home dashboard; banner and default preferences are manual steps (no REST endpoint) | `showcase`, `showcase-check`, `seed-showcase`, `unseed-showcase` |
| `estates/drift.py` | Diode ingest → Assurance deviations | observed projection of drifted records only | `drift`, `drift-check`, `drift-ingest` |

Plugins present on Cloud tenants but deliberately not authored: NDX
enrichments (vendor lifecycle data; import from the catalog, never invent),
Validation results/findings/scores (engine output; the validation sidecar
authors only policies and rules and runs them), Labs Console checkpoints (platform telemetry).
Official API notes for each plugin: `.claude/skills/netbox-labs-skills`.
"""


def delivery(kind):
    tags = []
    if kind in turbobulk.PLUGIN_CREATE_KINDS or kind in turbobulk.REST_CREATE_KINDS:
        tags.append("REST")
    else:
        tags.append("TB")
    if kind in diode.LOADER_ONLY_KINDS:
        tags.append("loader-only")
    if kind in turbobulk.MAIN_SCOPED_KINDS:
        tags.append("main")
    if kind in naming.NAMESPACED_KINDS:
        tags.append("ns-name")
    if kind in naming.IDENTITY_NAMED_KINDS:
        tags.append("id-name")
    return ", ".join(tags)


def identity(kind):
    if kind in diode.LOADER_ONLY_KINDS:
        return "—"
    if kind not in diode._IDENTITY:
        return "SDK default"
    fields, scope = diode._IDENTITY[kind]
    text = " + ".join(fields) or "the pair"
    return f"{text} (in {', '.join(scope)})" if scope else text


def render():
    rows = []
    for kind in sorted(turbobulk.SPECS):
        model, endpoint = turbobulk.SPECS[kind]
        refs = ", ".join(sorted(turbobulk.SUPPORTED_REFS.get(kind, ()))) or "—"
        rows.append(f"| `{kind}` | `{model}` | `{endpoint}` | {refs} | {identity(kind)} | {delivery(kind)} |")
    return HEAD + "\n".join(rows) + "\n" + TAIL


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    text = render()
    if argv[:1] == ["--check"]:
        if DOC.read_text() != text:
            sys.exit(f"{DOC} is stale: run `just schema-map`")
        return
    DOC.write_text(text)
    print(f"wrote {DOC} ({len(turbobulk.SPECS)} kinds)")


if __name__ == "__main__":
    main()
